language: python
dist: trusty

services:
  - docker

before_install:
  - docker build -t jumpscale .

script:
  - docker run --rm -t jumpscale /bin/bash -c "source /sandbox/env.sh; pytest -v /sandbox/code/github/threefoldtech/digitalmeX/DigitalMe"

after_success:
  - docker run --rm -t jumpscale /bin/bash -c "codecov"

notifications:
  webhooks:
      urls:
          - "https://scalar.vector.im/api/neb/services/hooks/dHJhdmlzLWNpLyU0MHphaWJvbiUzQW1hdHJpeC5vcmcvJTIxaVhJdURCb05OdXdXUk51T2NkJTNBbWF0cml4Lm9yZw"
      on_success: change  # always|never|change
      on_failure: always
      on_start: never