

@url = threebot.settings
doubleName* = ""
firstName* = ""
lastName = ""                
email* = ""         
addressStreet = ""  
addressNumber = ""
addressZipcode = ""
addressCity = ""                     
addressCountry* = "" 
telephone = ""



